### ISSUE TITLE
Screen blur

### ISSUE THREAD

**Issue by zuozhehao** [Sunoo/homebridge-camera-ffmpeg#638]
Node.js  | v12.18.2
Npm  | v6.14.6
homebridge-camera-ffmpeg v2.1.1
raspberry 4b  4G RAM
```
{
	"name": "大门左侧",
	"videoConfig": {
		"source": "-re -i rtsp://admin:admin@192.168.1.21/cam/realmonitor?channel=1&subtype=0",
		"vcodec": "h264",
		"debug": true
	}
}
```

**Comment by Sunoo** [comment]
Sorry, it’s not clear what problem you’re experiencing. What version of iOS are you running? Can you see the video if you try to load the URL in VLC? Is anything being logged in Homebridge?

**Comment by zuozhehao** [comment]
Iphone(13.5.1) and  mac(10.15.5) same problem.
---
I can watch videos normally in VLC.

**Comment by Sunoo** [comment]
Was this working in previous versions of this plugin? Or is this the first time you’re setting this up?

Please provide logs from Homebridge, preferably in debug mode.

**Comment by zuozhehao** [comment]
@Sunoo I installed this plug-in for the first time.
[log.txt](https://github.com/homebridge-plugins/homebridge-camera-ffmpeg/files/4907016/log.txt)

**Comment by zuozhehao** [comment]
I remove all homekit devices from my phone and I re installed the homebridge and homebridge-camera-ffmpeg 。
But I couldn't find the camera device in homekit。
```
{
    "bridge": {
        "name": "Homebridge",
        "username": "xxxxxxxx",
        "port": 51991,
        "pin": "xxx-xx-xxx"
    },
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "zh-CN",
            "platform": "config"
        },
        {
            "cameras": [
                {
                    "name": "camera-test",
                    "videoConfig": {
                        "source": "-re -i rtsp://admin:admin@192.168.1.22/cam/realmonitor?channel=1&subtype=0",
                        "vcodec": "h264_omx",
                        "debug": true
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
    ],
    "accessories": []
}
```
--------

[7/11/2020, 16:58:33] Loaded plugin: homebridge-camera-ffmpeg@2.2.0
[7/11/2020, 16:58:33] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[7/11/2020, 16:58:33] ---
[7/11/2020, 16:58:34] Loaded plugin: homebridge-config-ui-x@4.23.2
[7/11/2020, 16:58:34] Registering platform 'homebridge-config-ui-x.config'
[7/11/2020, 16:58:34] ---
[7/11/2020, 16:58:34] Loading 2 platforms...
[7/11/2020, 16:58:34] [Config] Initializing config platform...
[7/11/2020, 16:58:34] [Config] Running in Service Mode
[7/11/2020, 16:58:34] [Camera-ffmpeg] Initializing Camera-ffmpeg platform...
[7/11/2020, 16:58:34] [Camera-ffmpeg] Configuring accessory camera-test
Setup Payload:
X-HM://0024G1G1111111
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ xxx-xx-xxx │     
    └────────────┘     
                       
[7/11/2020, 16:58:34] Homebridge is running on port 51991.

**Comment by Sunoo** [comment]
@zuozhehao Version 2.2.0 had an issue that prevented Homebridge from starting in some cases (#640). That was resolved in version 2.2.1. Sorry about that.

**Comment by zuozhehao** [comment]
@Sunoo 
I updated to 2.2.1, the problem still exists.
<img width="319" alt="WX20200712-010747@2x" src="https://user-images.githubusercontent.com/4464252/87229674-b2e82080-c3dc-11ea-80a6-086096f9a2fe.png">

[log.txt](https://github.com/homebridge-plugins/homebridge-camera-ffmpeg/files/4907281/log.txt)

**Comment by Sunoo** [comment]
I haven't had a chance to sift through the log file you provided yet. Hoping to get to that soon and see I can work out what's going wrong.

**Comment by zuozhehao** [comment]
> I haven't had a chance to sift through the log file you provided yet. Hoping to get to that soon and see I can work out what's going wrong.

Can you see the log file I uploaded. The file name is log.txt

[log.txt](https://github.com/homebridge-plugins/homebridge-camera-ffmpeg/files/4907329/log.txt)

**Comment by Sunoo** [comment]
Yep, I see the file, just haven't had the chance to look through it and try to understand what is failing yet.

**Comment by zuozhehao** [comment]
> Yep, I see the file, just haven't had the chance to look through it and try to understand what is failing yet.

okay, thank you.

**Comment by Sunoo** [comment]
From your logs, it looks like FFmpeg is able to connect to your camera just fine, not sure why you aren’t seeing any video in the Home app.

**Comment by zuozhehao** [comment]
> From your logs, it looks like FFmpeg is able to connect to your camera just fine, not sure why you aren’t seeing any video in the Home app.

I can see the video is that the first 2 seconds of the picture is normal, most of the latter picture is gray

**Comment by Sunoo** [comment]
Oh interesting, I didn’t realize that it worked for a bit before looking like that.

You could try adding `-fflags +discardcorrupt` to the beginning of your ‘source’ config option to see if that helps.

**Comment by zuozhehao** [comment]
I'm not sure it has anything to do with my camera. It's a HD camera that looks out on the road.

**Comment by Sunoo** [comment]
Can you please try what I suggested.

**Comment by zuozhehao** [comment]
> Can you please try what I suggested.
Okay, thank you. But I'm working now. I may need to go back to the test on the weekend.

**Comment by Sunoo** [comment]
I also just noticed you have `-re` in your 'source' option, this can cause packet loss and typically should not be used, so I’d recommend removing that and trying again.

**Comment by zuozhehao** [comment]
> I also just noticed you have `-re` in your 'source' option, this can cause packet loss and typically should not be used, so I’d recommend removing that and trying again.

I try to delete the parameter `-re`, but the problem still exists. I try to add the parameter `-fflags +discardcorropt` Homekit shows no response

**Comment by Sunoo** [comment]
I improved the debug logging in the new version, could you upgrade to the latest version and submit a new log?

It might just be an issue with your camera though... Could you tell me what manufacturer and model of camera you have so I can try to find if anyone else is encountering problems?
